Create list of tasks
kamilgadek/to_do_list_kamilg pull request #14
Opened 2024-08-20 09:57 UTC by kamilgadek

It's hardcode list of tasks and it will be delated (it's only for learning purpose)

2024-08-20 11:15 UTC, mszakacz requested changes
1) In this PR we have to create a list of tasks, creating the Task class is another Issue and should be another PR. Probably it's event better to start from moving the Task class.
2) tasks list should be create in seprate file and separate folder, not in the model itself.
3) Please remember that Task model should be created in package/src/models/task.dart

What I would suggest here is to rename the PR from creating a list of tasks to "move the Task model to tasks_repository", for that we should include the change that the Task was moved from lib models to package models, and do not include tasks data in this PR.

2024-08-20 11:44 UTC, kamilgadek commented
Okay, I've uploaded the changes. Please check them.

2024-08-20 11:59 UTC, mszakacz requested changes

2024-08-20 11:59 UTC, mszakacz commented on packages/src/models/task.dart
That's the only change we want to have in this PR (as PR name suggests)

2024-08-20 12:00 UTC, mszakacz commented on packages/src/models/task.dart
@kamilgadek

2024-08-20 12:07 UTC, kamilgadek commented on packages/src/models/task.dart
Can you tell me how i can remove all other changes? Can i just delete commit?

2024-08-20 12:13 UTC, mszakacz commented on packages/src/models/task.dart
@kamilgadek You should be able to revert commits, but You should check the correct way to do it.
However, Your other changes are pretty simple - you just deleted the file - so you can copy all the code and paste it again in VS Code, so when you push it to this branch, it will be no code change - maybe not the most elegant way, but for sure will work.

2024-08-20 12:14 UTC, mszakacz commented on packages/src/models/task.dart
@kamilgadek As you see, such a cooperation will teach you git skills first, as you didn't have a change to practice them while working alone.

2024-08-20 12:52 UTC, kamilgadek commented on packages/src/models/task.dart
Pls check. Yes thats a great practice thank you for that.

2024-08-23 18:51 UTC, mszakacz requested changes
Please go to PR>Files changed. You have 2 files there, but none of them is `task.dart`.
Please note that the `task.dart` is the ONLY file that should be added to this PR. No other file change should be there. Ping me if help needed.

2024-08-23 18:51 UTC, mszakacz commented on packages/src/models/task.dart
@kamilgadek What happened with task.dart file?? **task.dart the only file that should be added to this PR**, nothing else. Do you have it saved anywhere? We can schedule a call to fix it briefly.

2024-08-24 11:04 UTC, kamilgadek commented on packages/src/models/task.dart
Yes i have got task.dart saved

class Task {
  final String title;
  final String description;
  final bool isDone;

  Task({
    required this.title,
    required this.description,
    required this.isDone,
  });
}

List<Task> tasks = [
  Task(
    title: 'Task 1', 
    description: 'Lear Flutter', 
    isDone: false,
  ),
  Task(
    title: 'Task 2', 
    description: 'Clean room', 
    isDone: true,
  ),
  Task(
    title: 'Task 3', 
    description: 'Go to the gym', 
    isDone: false,
  ),
];

2024-08-25 06:42 UTC, closed without merging