refactor(database): edit methods AddTasks and getTasks
kamilgadek/to_do_list_kamilg pull request #52
Opened 2024-11-14 18:52 UTC by kamilgadek

2024-11-17 21:54 UTC, mszakacz approved these changes
@kamilgadek pretty good. Did you try to test in (run main.dart), but do not pass empty json while `addTask`. you can try to pass sth like this:
```
await localStorage.addDocument(
collection: 'Tasks',
document: {
    'task': 'Buy milk',
    'isDone': false,
},
);
```
and then try to read this document again

2024-11-19 17:42 UTC, kamilgadek commented
@mszakacz 
Thank you for the suggestion! I updated the onCreate method in my code i have got content and status columns in the database schema. Then, I tested it by adding a document like this:


await localStorage.addDocument(
  collection: 'Tasks',
  document: {
    'content': 'Buy milk',
    'status': 0,
  },
);

2024-11-23 09:19 UTC, mszakacz requested changes
few comments, and please rename PR name - it should be a package name in the brackets (we don't have a `database` package)

2024-11-23 09:19 UTC, mszakacz commented on lib/main.dart
> +  final localStorage = LocalStorage(databaseName: 'tasks.db');
databaseName should not be declared in main. It should be declared in tasks_repository.

2024-11-23 09:19 UTC, mszakacz commented on lib/main.dart
> +    final tasksAfterDelete = await localStorage.getDocuments(collection: 'tasks');
same here

2024-11-23 09:19 UTC, mszakacz commented on packages/local_storage/lib/src/local_storage.dart
> +            status INTEGER NOT NULL
status can be bool? Or bool is not supported?

2024-11-23 09:19 UTC, mszakacz commented on packages/local_storage/lib/src/local_storage.dart
> +            status INTEGER NOT NULL
I don't know what to do with this peace of code. I don't like you create tasks table in LocalStorage. It's important to understand that LocalStorage is something abstract - it should not mention task anywhere. You should use LocalStorage in TasksRepository and there adjust to your needs - give a database name and properties, names of columns. I'm not sure how to achieve it with this particular package. Wait- look at the example before change - in lines 29-32 you use variables. That means you can try to write a method createDatabase which creates database based on given parameters and returns database instance. Let's create such a method. Remember: every tasks related settings should be made in TasksRepository, but you have to make LocalStorage flexible enough to make such a settings there.

2024-11-23 09:19 UTC, mszakacz commented on packages/local_storage/lib/src/local_storage.dart
> +    required Map<String, dynamic> document,
as we use SQL in this code and we have 'CREATE TABLE' command, it may be easier to understand this code if we stick to table convention.

2024-11-23 09:19 UTC, mszakacz commented on packages/local_storage/lib/src/local_storage.dart
>    }
again. We are in LocalStorage - we should not have any task related methods here - we should have it in TasksRepository instead.

2024-11-23 09:19 UTC, mszakacz commented on packages/tasks_repository/lib/src/tasks_repository.dart
> +    await localStorage.deleteTask(taskId);
make necessary changes to use localStorage.deleteDoc

2024-11-25 09:07 UTC, mszakacz requested changes
Hey. Please read my previous longest comment one more time as I have you a solution there. You should do everything on repository side. But make LocalStorage flexible enough to make it possible.

2024-11-25 09:07 UTC, mszakacz commented on packages/local_storage/lib/src/local_storage.dart
> +            status INTEGER NOT NULL
@kamilgadek 
make it a function (method) instead of getter and pass needed parameters, from where you would know the columns??

2024-11-25 09:07 UTC, mszakacz commented on packages/local_storage/lib/src/local_storage.dart
> +    required Map<String, dynamic> document,
probably passing db would be needed

2024-12-15 09:31 UTC, merged